# Generated by Django 4.2.3 on 2023-09-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_account', '0007_skillset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillset',
            name='level',
            field=models.CharField(max_length=100),
        ),
    ]
