# Generated by Django 4.2.3 on 2023-09-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_account', '0009_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
