# Generated by Django 4.2.3 on 2023-09-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_account', '0014_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='average_rating',
        ),
    ]
