# Generated by Django 4.2.3 on 2023-09-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_account', '0015_remove_projects_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
