# Generated by Django 4.2.3 on 2023-09-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_account', '0017_userprofile_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
